const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Challenge = require("./models/Challenge");

dotenv.config();

const challenges = [
  // DAYS 1 to 10 - EASY
  {
    day: 1,
    week: 1,
    difficulty: "Easy",
    title: "Sum of Two Numbers",
    description: "Accept two space-separated integers. Print the sum of the two integers.",
    exampleInput1: "5 7",
    exampleOutput1: "12",
    exampleInput2: "10 -2",
    exampleOutput2: "8",
    maxExecutionTime: 2000,
    testCases: [
      { input: "5 7", output: "12", isHidden: false },
      { input: "10 -2", output: "8", isHidden: false },
      { input: "-5 -5", output: "-10", isHidden: true },
      { input: "100 250", output: "350", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim();\nconst [a, b] = input.split(' ').map(Number);\nconsole.log(a + b);`,
      python: `import sys\ninput_data = sys.stdin.read().strip()\na, b = map(int, input_data.split())\nprint(a + b)`,
      c: `#include <stdio.h>\n\nint main() {\n    int a, b;\n    if (scanf("%d %d", &a, &b) == 2) {\n        printf("%d\\n", a + b);\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b;\n    if (cin >> a >> b) {\n        cout << a + b << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\n\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int a = sc.nextInt();\n            int b = sc.nextInt();\n            System.out.println(a + b);\n        }\n    }\n}`,
    },
  },
  {
    day: 2,
    week: 1,
    difficulty: "Easy",
    title: "Odd or Even",
    description: "Accept an integer. If the integer is even, print Even. Else print Odd.",
    exampleInput1: "4",
    exampleOutput1: "Even",
    exampleInput2: "7",
    exampleOutput2: "Odd",
    maxExecutionTime: 2000,
    testCases: [
      { input: "4", output: "Even", isHidden: false },
      { input: "7", output: "Odd", isHidden: false },
      { input: "0", output: "Even", isHidden: true },
      { input: "-15", output: "Odd", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim();\nconst num = parseInt(input);\nconsole.log(num % 2 === 0 ? "Even" : "Odd");`,
      python: `import sys\nnum = int(sys.stdin.read().strip())\nprint("Even" if num % 2 == 0 else "Odd")`,
      c: `#include <stdio.h>\n\nint main() {\n    int num;\n    if (scanf("%d", &num) == 1) {\n        if (num % 2 == 0) {\n            printf("Even\\n");\n        } else {\n            printf("Odd\\n");\n        }\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\nusing namespace std;\n\nint main() {\n    int num;\n    if (cin >> num) {\n        cout << (num % 2 == 0 ? "Even" : "Odd") << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\n\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int num = sc.nextInt();\n            System.out.println(num % 2 == 0 ? "Even" : "Odd");\n        }\n    }\n}`,
    },
  },
  {
    day: 3,
    week: 1,
    difficulty: "Easy",
    title: "Equal Sum Check",
    description: "Accept four integers. Print Yes if the sum of the first two equals the sum of the last two. Else print No.",
    exampleInput1: "2 3 4 1",
    exampleOutput1: "Yes",
    exampleInput2: "10 15 16 8",
    exampleOutput2: "No",
    maxExecutionTime: 2000,
    testCases: [
      { input: "2 3 4 1", output: "Yes", isHidden: false },
      { input: "10 15 16 8", output: "No", isHidden: false },
      { input: "5 5 8 2", output: "Yes", isHidden: true },
      { input: "0 0 1 0", output: "No", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim();\nconst [a, b, c, d] = input.split(' ').map(Number);\nconsole.log(a + b === c + d ? "Yes" : "No");`,
      python: `import sys\na, b, c, d = map(int, sys.stdin.read().strip().split())\nprint("Yes" if a + b == c + d else "No")`,
      c: `#include <stdio.h>\n\nint main() {\n    int a, b, c, d;\n    if (scanf("%d %d %d %d", &a, &b, &c, &d) == 4) {\n        printf("%s\\n", (a + b == c + d) ? "Yes" : "No");\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b, c, d;\n    if (cin >> a >> b >> c >> d) {\n        cout << ((a + b == c + d) ? "Yes" : "No") << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\n\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int a = sc.nextInt();\n            int b = sc.nextInt();\n            int c = sc.nextInt();\n            int d = sc.nextInt();\n            System.out.println(a + b == c + d ? "Yes" : "No");\n        }\n    }\n}`,
    },
  },
  {
    day: 4,
    week: 1,
    difficulty: "Easy",
    title: "Maximum of Three",
    description: "Accept three integers. Print the maximum value among them.",
    exampleInput1: "12 45 7",
    exampleOutput1: "45",
    exampleInput2: "-5 -2 -10",
    exampleOutput2: "-2",
    maxExecutionTime: 2000,
    testCases: [
      { input: "12 45 7", output: "45", isHidden: false },
      { input: "-5 -2 -10", output: "-2", isHidden: false },
      { input: "100 100 50", output: "100", isHidden: true },
      { input: "3 9 15", output: "15", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim();\nconst nums = input.split(' ').map(Number);\nconsole.log(Math.max(...nums));`,
      python: `import sys\nnums = list(map(int, sys.stdin.read().strip().split()))\nprint(max(nums))`,
      c: `#include <stdio.h>\n\nint main() {\n    int a, b, c;\n    if (scanf("%d %d %d", &a, &b, &c) == 3) {\n        int max = a;\n        if (b > max) max = b;\n        if (c > max) max = c;\n        printf("%d\\n", max);\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int a, b, c;\n    if (cin >> a >> b >> c) {\n        cout << max({a, b, c}) << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\n\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int a = sc.nextInt();\n            int b = sc.nextInt();\n            int c = sc.nextInt();\n            System.out.println(Math.max(a, Math.max(b, c)));\n        }\n    }\n}`,
    },
  },
  {
    day: 5,
    week: 1,
    difficulty: "Easy",
    title: "Celsius to Fahrenheit",
    description: "Accept temperature in Celsius (integer). Output the converted Fahrenheit temperature (rounded to integer). Formula: F = C * 9/5 + 32",
    exampleInput1: "25",
    exampleOutput1: "77",
    exampleInput2: "0",
    exampleOutput2: "32",
    maxExecutionTime: 2000,
    testCases: [
      { input: "25", output: "77", isHidden: false },
      { input: "0", output: "32", isHidden: false },
      { input: "-40", output: "-40", isHidden: true },
      { input: "37", output: "99", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim();\nconst c = parseInt(input);\nconsole.log(Math.round(c * 9 / 5 + 32));`,
      python: `import sys\nc = int(sys.stdin.read().strip())\nprint(round(c * 9 / 5 + 32))`,
      c: `#include <stdio.h>\n\nint main() {\n    int c;\n    if (scanf("%d", &c) == 1) {\n        double f = c * 9.0 / 5.0 + 32.0;\n        printf("%.0f\\n", f);\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <cmath>\nusing namespace std;\n\nint main() {\n    int c;\n    if (cin >> c) {\n        double f = c * 9.0 / 5.0 + 32.0;\n        cout << round(f) << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\n\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int c = sc.nextInt();\n            System.out.println(Math.round(c * 9.0 / 5.0 + 32.0));\n        }\n    }\n}`,
    },
  },
  {
    day: 6,
    week: 1,
    difficulty: "Easy",
    title: "Leap Year Checker",
    description: "Accept a year (integer). Print Yes if it is a leap year, otherwise No.",
    exampleInput1: "2020",
    exampleOutput1: "Yes",
    exampleInput2: "1900",
    exampleOutput2: "No",
    maxExecutionTime: 2000,
    testCases: [
      { input: "2020", output: "Yes", isHidden: false },
      { input: "1900", output: "No", isHidden: false },
      { input: "2000", output: "Yes", isHidden: true },
      { input: "2023", output: "No", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim();\nconst year = parseInt(input);\nconst isLeap = (year % 4 === 0 && year % 100 !== 0) || (year % 400 === 0);\nconsole.log(isLeap ? "Yes" : "No");`,
      python: `import sys\nyear = int(sys.stdin.read().strip())\nis_leap = (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)\nprint("Yes" if is_leap else "No")`,
      c: `#include <stdio.h>\n\nint main() {\n    int year;\n    if (scanf("%d", &year) == 1) {\n        int isLeap = (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);\n        printf("%s\\n", isLeap ? "Yes" : "No");\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\nusing namespace std;\n\nint main() {\n    int year;\n    if (cin >> year) {\n        bool isLeap = (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);\n        cout << (isLeap ? "Yes" : "No") << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\n\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int year = sc.nextInt();\n            boolean isLeap = (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);\n            System.out.println(isLeap ? "Yes" : "No");\n        }\n    }\n}`,
    },
  },
  {
    day: 7,
    week: 1,
    difficulty: "Easy",
    title: "Factorial of a Number",
    description: "Accept a non-negative integer N. Print the factorial of N.",
    exampleInput1: "5",
    exampleOutput1: "120",
    exampleInput2: "0",
    exampleOutput2: "1",
    maxExecutionTime: 2000,
    testCases: [
      { input: "5", output: "120", isHidden: false },
      { input: "0", output: "1", isHidden: false },
      { input: "6", output: "720", isHidden: true },
      { input: "10", output: "3628800", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst n = parseInt(fs.readFileSync(0, 'utf-8').trim());\nlet fact = 1;\nfor (let i = 1; i <= n; i++) fact *= i;\nconsole.log(fact);`,
      python: `import sys\nn = int(sys.stdin.read().strip())\nfact = 1\nfor i in range(1, n + 1): fact *= i\nprint(fact)`,
      c: `#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf("%d", &n) == 1) {\n        long long fact = 1;\n        for (int i = 1; i <= n; i++) fact *= i;\n        printf("%lld\\n", fact);\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    if (cin >> n) {\n        long long fact = 1;\n        for (int i = 1; i <= n; i++) fact *= i;\n        cout << fact << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\n\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int n = sc.nextInt();\n            long fact = 1;\n            for (int i = 1; i <= n; i++) fact *= i;\n            System.out.println(fact);\n        }\n    }\n}`,
    },
  },
  {
    day: 8,
    week: 1,
    difficulty: "Easy",
    title: "Nth Fibonacci Number",
    description: "Accept an integer N. Print the Nth Fibonacci number (where F(1) = 1, F(2) = 1, F(3) = 2...).",
    exampleInput1: "6",
    exampleOutput1: "8",
    exampleInput2: "1",
    exampleOutput2: "1",
    maxExecutionTime: 2000,
    testCases: [
      { input: "6", output: "8", isHidden: false },
      { input: "1", output: "1", isHidden: false },
      { input: "10", output: "55", isHidden: true },
      { input: "15", output: "610", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst n = parseInt(fs.readFileSync(0, 'utf-8').trim());\nif (n <= 2) { console.log(1); process.exit(0); }\nlet a = 1, b = 1, c = 0;\nfor (let i = 3; i <= n; i++) { c = a + b; a = b; b = c; }\nconsole.log(b);`,
      python: `import sys\nn = int(sys.stdin.read().strip())\nif n <= 2:\n    print(1)\nelse:\n    a, b = 1, 1\n    for _ in range(3, n + 1):\n        a, b = b, a + b\n    print(b)`,
      c: `#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf("%d", &n) == 1) {\n        if (n <= 2) {\n            printf("1\\n");\n        } else {\n            long long a = 1, b = 1, temp;\n            for (int i = 3; i <= n; i++) {\n                temp = a + b;\n                a = b;\n                b = temp;\n            }\n            printf("%lld\\n", b);\n        }\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    if (cin >> n) {\n        long long fact = 1;\n        long long a = 1, b = 1, temp;\n        if (n <= 2) { cout << 1 << endl; return 0; }\n        for (int i = 3; i <= n; i++) {\n            temp = a + b; a = b; b = temp;\n        }\n        cout << b << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\n\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int n = sc.nextInt();\n            if (n <= 2) { System.out.println(1); return; }\n            long a = 1, b = 1, temp;\n            for (int i = 3; i <= n; i++) {\n                temp = a + b; a = b; b = temp;\n            }\n            System.out.println(b);\n        }\n    }\n}`,
    },
  },
  {
    day: 9,
    week: 2,
    difficulty: "Easy",
    title: "Palindrome Word",
    description: "Accept a string. Print Yes if it is a palindrome (case insensitive), otherwise No.",
    exampleInput1: "radar",
    exampleOutput1: "Yes",
    exampleInput2: "Hello",
    exampleOutput2: "No",
    maxExecutionTime: 2000,
    testCases: [
      { input: "radar", output: "Yes", isHidden: false },
      { input: "Hello", output: "No", isHidden: false },
      { input: "Madam", output: "Yes", isHidden: true },
      { input: "A", output: "Yes", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst word = fs.readFileSync(0, 'utf-8').trim().toLowerCase();\nconst reversed = word.split('').reverse().join('');\nconsole.log(word === reversed ? "Yes" : "No");`,
      python: `import sys\nword = sys.stdin.read().strip().lower()\nprint("Yes" if word == word[::-1] else "No")`,
      c: `#include <stdio.h>\n#include <string.h>\n#include <ctype.h>\n\nint main() {\n    char word[100];\n    if (scanf("%s", word) == 1) {\n        int len = strlen(word);\n        int isPal = 1;\n        for (int i = 0; i < len / 2; i++) {\n            if (tolower(word[i]) != tolower(word[len - 1 - i])) {\n                isPal = 0; break;\n            }\n        }\n        printf("%s\\n", isPal ? "Yes" : "No");\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <string>\n#include <algorithm>\n#include <cctype>\nusing namespace std;\n\nint main() {\n    string word;\n    if (cin >> word) {\n        string rev = word;\n        reverse(rev.begin(), rev.end());\n        bool isPal = true;\n        for (size_t i = 0; i < word.length(); i++) {\n            if (tolower(word[i]) != tolower(rev[i])) { isPal = false; break; }\n        }\n        cout << (isPal ? "Yes" : "No") << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\n\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNext()) {\n            String word = sc.next().toLowerCase();\n            String rev = new StringBuilder(word).reverse().toString();\n            System.out.println(word.equals(rev) ? "Yes" : "No");\n        }\n    }\n}`,
    },
  },
  {
    day: 10,
    week: 2,
    difficulty: "Easy",
    title: "Count Vowels",
    description: "Accept a string. Print the count of vowels (a, e, i, o, u - case insensitive) inside the string.",
    exampleInput1: "Sky Tech Makers",
    exampleOutput1: "4",
    exampleInput2: "c++",
    exampleOutput2: "0",
    maxExecutionTime: 2000,
    testCases: [
      { input: "Sky Tech Makers", output: "4", isHidden: false },
      { input: "c++", output: "0", isHidden: false },
      { input: "AEIOU", output: "5", isHidden: true },
      { input: "Testing", output: "2", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst str = fs.readFileSync(0, 'utf-8').trim().toLowerCase();\nconst matches = str.match(/[aeiou]/g);\nconsole.log(matches ? matches.length : 0);`,
      python: `import sys\nstr_data = sys.stdin.read().strip().lower()\nvowels = 'aeiou'\nprint(sum(1 for char in str_data if char in vowels))`,
      c: `#include <stdio.h>\n#include <ctype.h>\n\nint main() {\n    char ch;\n    int count = 0;\n    while ((ch = getchar()) != EOF) {\n        char low = tolower(ch);\n        if (low == 'a' || low == 'e' || low == 'i' || low == 'o' || low == 'u') count++;\n    }\n    printf("%d\\n", count);\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <string>\n#include <cctype>\nusing namespace std;\n\nint main() {\n    string s;\n    getline(cin, s);\n    int count = 0;\n    for(char c : s) {\n        char low = tolower(c);\n        if (low == 'a' || low == 'e' || low == 'i' || low == 'o' || low == 'u') count++;\n    }\n    cout << count << endl;\n    return 0;\n}`,
      java: `import java.util.Scanner;\n\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextLine()) {\n            String s = sc.nextLine().toLowerCase();\n            int count = 0;\n            for (int i = 0; i < s.length(); i++) {\n                char c = s.charAt(i);\n                if (c == 'a' || c == 'e' || c == 'i' || c == 'o' || c == 'u') count++;\n            }\n            System.out.println(count);\n        }\n    }\n}`,
    },
  },

  // DAYS 11 to 20 - MEDIUM
  {
    day: 11,
    week: 2,
    difficulty: "Medium",
    title: "Reverse a String",
    description: "Accept a string. Print the reversed string.",
    exampleInput1: "hello",
    exampleOutput1: "olleh",
    exampleInput2: "1234",
    exampleOutput2: "4321",
    maxExecutionTime: 2000,
    testCases: [
      { input: "hello", output: "olleh", isHidden: false },
      { input: "1234", output: "4321", isHidden: false },
      { input: "a", output: "a", isHidden: true },
      { input: "SkyTech", output: "hceTykS", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst str = fs.readFileSync(0, 'utf-8').trim();\nconsole.log(str.split('').reverse().join(''));`,
      python: `import sys\nstr_data = sys.stdin.read().strip()\nprint(str_data[::-1])`,
      c: `#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char str[1000];\n    if (fgets(str, sizeof(str), stdin)) {\n        int len = strlen(str);\n        while(len > 0 && (str[len-1] == '\\n' || str[len-1] == '\\r')) {\n            str[--len] = '\\0';\n        }\n        for (int i = len - 1; i >= 0; i--) putchar(str[i]);\n        putchar('\\n');\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    string s;\n    if (getline(cin, s)) {\n        reverse(s.begin(), s.end());\n        cout << s << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\n\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextLine()) {\n            String s = sc.nextLine();\n            System.out.println(new StringBuilder(s).reverse().toString());\n        }\n    }\n}`,
    },
  },
  {
    day: 12,
    week: 2,
    difficulty: "Medium",
    title: "FizzBuzz List",
    description: "Accept an integer N. Print space-separated numbers from 1 to N, replacing multiples of 3 with Fizz, multiples of 5 with Buzz, and multiples of both with FizzBuzz.",
    exampleInput1: "5",
    exampleOutput1: "1 2 Fizz 4 Buzz",
    exampleInput2: "15",
    exampleOutput2: "1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz",
    maxExecutionTime: 2000,
    testCases: [
      { input: "5", output: "1 2 Fizz 4 Buzz", isHidden: false },
      { input: "15", output: "1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz", isHidden: false },
      { input: "3", output: "1 2 Fizz", isHidden: true },
      { input: "1", output: "1", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst n = parseInt(fs.readFileSync(0, 'utf-8').trim());\nconst res = [];\nfor (let i = 1; i <= n; i++) {\n    if (i % 15 === 0) res.push("FizzBuzz");\n    else if (i % 3 === 0) res.push("Fizz");\n    else if (i % 5 === 0) res.push("Buzz");\n    else res.push(i);\n}\nconsole.log(res.join(' '));`,
      python: `import sys\nn = int(sys.stdin.read().strip())\nres = []\nfor i in range(1, n + 1):\n    if i % 15 == 0: res.append("FizzBuzz")\n    elif i % 3 == 0: res.append("Fizz")\n    elif i % 5 == 0: res.append("Buzz")\n    else: res.append(str(i))\nprint(' '.join(res))`,
      c: `#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf("%d", &n) == 1) {\n        for (int i = 1; i <= n; i++) {\n            if (i % 15 == 0) printf("FizzBuzz");\n            else if (i % 3 == 0) printf("Fizz");\n            else if (i % 5 == 0) printf("Buzz");\n            else printf("%d", i);\n            if (i < n) printf(" ");\n        }\n        printf("\\n");\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    if (cin >> n) {\n        for (int i = 1; i <= n; i++) {\n            if (i % 15 == 0) cout << "FizzBuzz";\n            else if (i % 3 == 0) cout << "Fizz";\n            else if (i % 5 == 0) cout << "Buzz";\n            else cout << i;\n            if (i < n) cout << " ";\n        }\n        cout << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\n\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int n = sc.nextInt();\n            StringBuilder sb = new StringBuilder();\n            for (int i = 1; i <= n; i++) {\n                if (i % 15 == 0) sb.append("FizzBuzz");\n                else if (i % 3 == 0) sb.append("Fizz");\n                else if (i % 5 == 0) sb.append("Buzz");\n                else sb.append(i);\n                if (i < n) sb.append(" ");\n            }\n            System.out.println(sb.toString());\n        }\n    }\n}`,
    },
  },
  {
    day: 13,
    week: 2,
    difficulty: "Medium",
    title: "Prime Checker",
    description: "Accept an integer. Print Yes if prime, else print No.",
    exampleInput1: "17",
    exampleOutput1: "Yes",
    exampleInput2: "4",
    exampleOutput2: "No",
    maxExecutionTime: 2000,
    testCases: [
      { input: "17", output: "Yes", isHidden: false },
      { input: "4", output: "No", isHidden: false },
      { input: "1", output: "No", isHidden: true },
      { input: "7919", output: "Yes", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst n = parseInt(fs.readFileSync(0, 'utf-8').trim());\nfunction isPrime(num) {\n    if (num <= 1) return false;\n    for (let i = 2; i <= Math.sqrt(num); i++) {\n        if (num % i === 0) return false;\n    }\n    return true;\n}\nconsole.log(isPrime(n) ? "Yes" : "No");`,
      python: `import sys, math\nn = int(sys.stdin.read().strip())\ndef is_prime(num):\n    if num <= 1: return False\n    for i in range(2, int(math.sqrt(num)) + 1):\n        if num % i == 0: return False\n    return True\nprint("Yes" if is_prime(n) else "No")`,
      c: `#include <stdio.h>\n#include <math.h>\nint isPrime(int n) {\n    if (n <= 1) return 0;\n    for (int i = 2; i <= sqrt(n); i++) {\n        if (n % i == 0) return 0;\n    }\n    return 1;\n}\nint main() {\n    int n;\n    if (scanf("%d", &n) == 1) printf("%s\\n", isPrime(n) ? "Yes" : "No");\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <cmath>\nusing namespace std;\nbool isPrime(int n) {\n    if (n <= 1) return false;\n    for (int i = 2; i <= sqrt(n); i++) {\n        if (n % i == 0) return false;\n    }\n    return true;\n}\nint main() {\n    int n;\n    if (cin >> n) cout << (isPrime(n) ? "Yes" : "No") << endl;\n    return 0;\n}`,
      java: `import java.util.Scanner;\npublic class Temp {\n    public static boolean isPrime(int n) {\n        if (n <= 1) return false;\n        for (int i = 2; i <= Math.sqrt(n); i++) if (n % i == 0) return false;\n        return true;\n    }\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int n = sc.nextInt();\n            System.out.println(isPrime(n) ? "Yes" : "No");\n        }\n    }\n}`,
    },
  },
  {
    day: 14,
    week: 3,
    difficulty: "Medium",
    title: "Second Largest Element",
    description: "Accept space-separated integers. Print the second largest value.",
    exampleInput1: "10 20 4 45 99",
    exampleOutput1: "45",
    exampleInput2: "5 5 5 1",
    exampleOutput2: "1",
    maxExecutionTime: 2000,
    testCases: [
      { input: "10 20 4 45 99", output: "45", isHidden: false },
      { input: "5 5 5 1", output: "1", isHidden: false },
      { input: "12 35 1 10 34 1", output: "34", isHidden: true },
      { input: "-10 -20 -30", output: "-20", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst nums = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nconst unique = [...new Set(nums)].sort((a, b) => b - a);\nconsole.log(unique[1]);`,
      python: `import sys\nnums = list(map(int, sys.stdin.read().strip().split()))\nunique = sorted(list(set(nums)), reverse=True)\nprint(unique[1])`,
      c: `#include <stdio.h>\n#include <limits.h>\nint main() {\n    int num, max = INT_MIN, secMax = INT_MIN;\n    while (scanf("%d", &num) != EOF) {\n        if (num > max) { secMax = max; max = num; }\n        else if (num > secMax && num < max) { secMax = num; }\n    }\n    printf("%d\\n", secMax);\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <set>\nusing namespace std;\nint main() {\n    int val; set<int, greater<int>> s;\n    while (cin >> val) s.insert(val);\n    auto it = s.begin(); it++;\n    cout << *it << endl;\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        TreeSet<Integer> set = new TreeSet<>(Collections.reverseOrder());\n        while (sc.hasNextInt()) set.add(sc.nextInt());\n        Iterator<Integer> it = set.iterator();\n        if (it.hasNext()) it.next();\n        if (it.hasNext()) System.out.println(it.next());\n    }\n}`,
    },
  },
  {
    day: 15,
    week: 3,
    difficulty: "Medium",
    title: "Find Duplicate Elements",
    description: "Accept space-separated integers. Print duplicates in ascending order, or None.",
    exampleInput1: "1 2 3 2 1",
    exampleOutput1: "1 2",
    exampleInput2: "1 2 3",
    exampleOutput2: "None",
    maxExecutionTime: 2000,
    testCases: [
      { input: "1 2 3 2 1", output: "1 2", isHidden: false },
      { input: "1 2 3", output: "None", isHidden: false },
      { input: "4 4 4 5 6 5", output: "4 5", isHidden: true },
      { input: "9 9 9 9 9", output: "9", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst nums = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nconst counts = {};\nnums.forEach(n => counts[n] = (counts[n] || 0) + 1);\nconst dups = Object.keys(counts).filter(k => counts[k] > 1).map(Number).sort((a,b)=>a-b);\nconsole.log(dups.length > 0 ? dups.join(' ') : "None");`,
      python: `import sys\nnums = list(map(int, sys.stdin.read().strip().split()))\ncounts = {}\nfor n in nums: counts[n] = counts.get(n, 0) + 1\ndups = sorted([k for k, v in counts.items() if v > 1])\nprint(' '.join(map(str, dups)) if dups else "None")`,
      c: `#include <stdio.h>\n#include <stdlib.h>\nint cmp(const void *a, const void *b) { return (*(int*)a - *(int*)b); }\nint main() {\n    int arr[1000], n = 0; while (scanf("%d", &arr[n]) != EOF) n++;\n    qsort(arr, n, sizeof(int), cmp);\n    int dups[1000], dupCount = 0;\n    for (int i = 0; i < n - 1; i++) {\n        if (arr[i] == arr[i+1]) {\n            int added = 0; for (int j = 0; j < dupCount; j++) if (dups[j] == arr[i]) added = 1;\n            if (!added) dups[dupCount++] = arr[i];\n        }\n    }\n    if (dupCount == 0) printf("None\\n");\n    else {\n        for (int i = 0; i < dupCount; i++) printf("%d%s", dups[i], i < dupCount-1 ? " " : "");\n        printf("\\n");\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <map>\n#include <vector>\nusing namespace std;\nint main() {\n    int val; map<int, int> counts; while (cin >> val) counts[val]++;\n    vector<int> d;\n    for (auto const& [k, v] : counts) if (v > 1) d.push_back(k);\n    if (d.empty()) cout << "None" << endl;\n    else {\n        for (size_t i = 0; i < d.size(); i++) cout << d[i] << (i < d.size()-1 ? " " : "");\n        cout << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        Map<Integer, Integer> counts = new TreeMap<>();\n        while (sc.hasNextInt()) {\n            int n = sc.nextInt(); counts.put(n, counts.getOrDefault(n, 0) + 1);\n        }\n        List<String> d = new ArrayList<>();\n        for (var e : counts.entrySet()) if (e.getValue() > 1) d.add(String.valueOf(e.getKey()));\n        System.out.println(d.isEmpty() ? "None" : String.join(" ", d));\n    }\n}`,
    },
  },
  {
    day: 16,
    week: 3,
    difficulty: "Medium",
    title: "Two Sum Target",
    description: "Accept target sum followed by integers list. Print Yes if two elements sum to target, otherwise No.",
    exampleInput1: "9 2 7 11 15",
    exampleOutput1: "Yes",
    exampleInput2: "10 1 2 3 4",
    exampleOutput2: "No",
    maxExecutionTime: 2000,
    testCases: [
      { input: "9 2 7 11 15", output: "Yes", isHidden: false },
      { input: "10 1 2 3 4", output: "No", isHidden: false },
      { input: "20 10 5 15", output: "Yes", isHidden: true },
      { input: "5 2 2", output: "No", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nconst target = input[0];\nconst nums = input.slice(1);\nlet found = "No";\nconst seen = new Set();\nfor (let n of nums) {\n    if (seen.has(target - n)) { found = "Yes"; break; }\n    seen.add(n);\n}\nconsole.log(found);`,
      python: `import sys\nnums = list(map(int, sys.stdin.read().strip().split()))\ntarget = nums[0]\nseen = set()\nfound = "No"\nfor n in nums[1:]:\n    if (target - n) in seen: found = "Yes"; break\n    seen.add(n)\nprint(found)`,
      c: `#include <stdio.h>\nint main() {\n    int target, arr[1000], n = 0;\n    if (scanf("%d", &target) == 1) {\n        while (scanf("%d", &arr[n]) != EOF) n++;\n        int found = 0;\n        for (int i = 0; i < n; i++) {\n            for (int j = i + 1; j < n; j++) if (arr[i] + arr[j] == target) found = 1;\n        }\n        printf("%s\\n", found ? "Yes" : "No");\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <vector>\n#include <unordered_set>\nusing namespace std;\nint main() {\n    int target, val; if (cin >> target) {\n        vector<int> nums; while (cin >> val) nums.push_back(val);\n        unordered_set<int> seen; bool found = false;\n        for (int n : nums) {\n            if (seen.count(target - n)) { found = true; break; }\n            seen.insert(n);\n        }\n        cout << (found ? "Yes" : "No") << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int target = sc.nextInt();\n            Set<Integer> seen = new HashSet<>();\n            boolean found = false;\n            while (sc.hasNextInt()) {\n                int n = sc.nextInt();\n                if (seen.contains(target - n)) { found = true; break; }\n                seen.add(n);\n            }\n            System.out.println(found ? "Yes" : "No");\n        }\n    }\n}`,
    },
  },
  {
    day: 17,
    week: 3,
    difficulty: "Medium",
    title: "Valid Parentheses",
    description: "Accept a brackets string. Print Yes if correctly nested and closed, else print No.",
    exampleInput1: "()[]{}",
    exampleOutput1: "Yes",
    exampleInput2: "(]",
    exampleOutput2: "No",
    maxExecutionTime: 2000,
    testCases: [
      { input: "()[]{}", output: "Yes", isHidden: false },
      { input: "(]", output: "No", isHidden: false },
      { input: "({[]})", output: "Yes", isHidden: true },
      { input: "(((", output: "No", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst str = fs.readFileSync(0, 'utf-8').trim();\nconst stack = [];\nconst pairs = { ')': '(', '}': '{', ']': '[' };\nlet valid = "Yes";\nfor (let char of str) {\n    if (['(', '{', '['].includes(char)) stack.push(char);\n    else if (pairs[char]) {\n        if (stack.pop() !== pairs[char]) { valid = "No"; break; }\n    }\n}\nif (stack.length > 0) valid = "No";\nconsole.log(valid);`,
      python: `import sys\ns = sys.stdin.read().strip()\nstack = []\npairs = {')': '(', '}': '{', ']': '['}\nvalid = "Yes"\nfor char in s:\n    if char in '({[': stack.append(char)\n    elif char in pairs:\n        if not stack or stack.pop() != pairs[char]: valid = "No"; break\nif stack: valid = "No"\nprint(valid)`,
      c: `#include <stdio.h>\n#include <string.h>\nint main() {\n    char s[1000];\n    if (scanf("%s", s) == 1) {\n        char stack[1000]; int top = -1, valid = 1;\n        for (int i = 0; s[i] != '\\0'; i++) {\n            char c = s[i];\n            if (c == '(' || c == '{' || c == '[') stack[++top] = c;\n            else {\n                if (top == -1) { valid = 0; break; }\n                char o = stack[top--];\n                if ((c == ')' && o != '(') || (c == '}' && o != '{') || (c == ']' && o != '[')) { valid = 0; break; }\n            }\n        }\n        if (top != -1) valid = 0;\n        printf("%s\\n", valid ? "Yes" : "No");\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <string>\n#include <stack>\nusing namespace std;\nint main() {\n    string s; if (cin >> s) {\n        stack<char> st; bool valid = true;\n        for (char c : s) {\n            if (c == '(' || c == '{' || c == '[') st.push(c);\n            else {\n                if (st.empty()) { valid = false; break; }\n                char t = st.top(); st.pop();\n                if ((c == ')' && t != '(') || (c == '}' && t != '{') || (c == ']' && t != '[')) { valid = false; break; }\n            }\n        }\n        if (!st.empty()) valid = false;\n        cout << (valid ? "Yes" : "No") << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNext()) {\n            String s = sc.next(); Stack<Character> st = new Stack<>(); boolean valid = true;\n            for (char c : s.toCharArray()) {\n                if (c == '(' || c == '{' || c == '[') st.push(c);\n                else {\n                    if (st.isEmpty()) { valid = false; break; }\n                    char t = st.pop();\n                    if ((c == ')' && t != '(') || (c == '}' && t != '{') || (c == ']' && t != '[')) { valid = false; break; }\n                }\n            }\n            if (!st.isEmpty()) valid = false;\n            System.out.println(valid ? "Yes" : "No");\n        }\n    }\n}`,
    },
  },
  {
    day: 18,
    week: 3,
    difficulty: "Medium",
    title: "Matrix Transpose",
    description: "Accept rows R and columns C, followed by matrix elements. Print the space-separated transposed matrix.",
    exampleInput1: "2 3 1 2 3 4 5 6",
    exampleOutput1: "1 4 2 5 3 6",
    exampleInput2: "2 2 1 2 3 4",
    exampleOutput2: "1 3 2 4",
    maxExecutionTime: 2000,
    testCases: [
      { input: "2 3 1 2 3 4 5 6", output: "1 4 2 5 3 6", isHidden: false },
      { input: "2 2 1 2 3 4", output: "1 3 2 4", isHidden: false },
      { input: "1 3 9 8 7", output: "9 8 7", isHidden: true },
      { input: "3 1 5 10 15", output: "5 10 15", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nconst r = input[0], c = input[1];\nconst matrix = [];\nlet k = 2;\nfor(let i=0; i<r; i++) {\n    matrix.push(input.slice(k, k+c));\n    k += c;\n}\nconst trans = [];\nfor(let j=0; j<c; j++) {\n    for(let i=0; i<r; i++) trans.push(matrix[i][j]);\n}\nconsole.log(trans.join(' '));`,
      python: `import sys\nvals = list(map(int, sys.stdin.read().strip().split()))\nr, c = vals[0], vals[1]\nmatrix = []\nk = 2\nfor i in range(r):\n    matrix.append(vals[k : k + c]); k += c\ntrans = []\nfor j in range(c):\n    for i in range(r): trans.append(str(matrix[i][j]))\nprint(' '.join(trans))`,
      c: `#include <stdio.h>\nint main() {\n    int r, c; if (scanf("%d %d", &r, &c) == 2) {\n        int m[100][100];\n        for (int i = 0; i < r; i++) for (int j = 0; j < c; j++) scanf("%d", &m[i][j]);\n        for (int j = 0; j < c; j++) {\n            for (int i = 0; i < r; i++) {\n                printf("%d", m[i][j]); if (j < c - 1 || i < r - 1) printf(" ");\n            }\n        }\n        printf("\\n");\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    int r, c; if (cin >> r >> c) {\n        vector<vector<int>> m(r, vector<int>(c));\n        for (int i = 0; i < r; i++) for (int j = 0; j < c; j++) cin >> m[i][j];\n        for (int j = 0; j < c; j++) {\n            for (int i = 0; i < r; i++) {\n                cout << m[i][j]; if (j < c - 1 || i < r - 1) cout << " ";\n            }\n        }\n        cout << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int r = sc.nextInt(); int c = sc.nextInt(); int[][] m = new int[r][c];\n            for (int i = 0; i < r; i++) for (int j = 0; j < c; j++) m[i][j] = sc.nextInt();\n            StringBuilder sb = new StringBuilder();\n            for (int j = 0; j < c; j++) {\n                for (int i = 0; i < r; i++) {\n                    sb.append(m[i][j]); if (j < c - 1 || i < r - 1) sb.append(" ");\n                }\n            }\n            System.out.println(sb.toString());\n        }\n    }\n}`,
    },
  },
  {
    day: 19,
    week: 3,
    difficulty: "Medium",
    title: "Longest Substring Without Repeating",
    description: "Accept a string. Print the length of the longest substring without repeating characters.",
    exampleInput1: "abcabcbb",
    exampleOutput1: "3",
    exampleInput2: "bbbbb",
    exampleOutput2: "1",
    maxExecutionTime: 2000,
    testCases: [
      { input: "abcabcbb", output: "3", isHidden: false },
      { input: "bbbbb", output: "1", isHidden: false },
      { input: "pwwkew", output: "3", isHidden: true },
      { input: "abcdefg", output: "7", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst s = fs.readFileSync(0, 'utf-8').trim();\nlet max = 0, start = 0; const seen = {};\nfor(let i=0; i<s.length; i++) {\n    if (seen[s[i]] >= start) start = seen[s[i]] + 1;\n    seen[s[i]] = i; max = Math.max(max, i - start + 1);\n}\nconsole.log(max);`,
      python: `import sys\ns = sys.stdin.read().strip()\nmax_len, start = 0, 0; seen = {}\nfor i, char in enumerate(s):\n    if char in seen and seen[char] >= start: start = seen[char] + 1\n    seen[char] = i; max_len = max(max_len, i - start + 1)\nprint(max_len)`,
      c: `#include <stdio.h>\n#include <string.h>\nint max(int a, int b) { return a > b ? a : b; }\nint main() {\n    char s[1000]; if (scanf("%s", s) == 1) {\n        int max_len = 0, start = 0, len = strlen(s);\n        int seen[256]; memset(seen, -1, sizeof(seen));\n        for (int i = 0; i < len; i++) {\n            if (seen[(unsigned char)s[i]] >= start) start = seen[(unsigned char)s[i]] + 1;\n            seen[(unsigned char)s[i]] = i; max_len = max(max_len, i - start + 1);\n        }\n        printf("%d\\n", max_len);\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <string>\n#include <vector>\n#include <algorithm>\nusing namespace std;\nint main() {\n    string s; if (cin >> s) {\n        int max_len = 0, start = 0; vector<int> seen(256, -1);\n        for (int i = 0; i < s.length(); i++) {\n            if (seen[s[i]] >= start) start = seen[s[i]] + 1;\n            seen[s[i]] = i; max_len = max(max_len, i - start + 1);\n        }\n        cout << max_len << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNext()) {\n            String s = sc.next(); int max = 0, start = 0; Map<Character, Integer> seen = new HashMap<>();\n            for (int i = 0; i < s.length(); i++) {\n                char c = s.charAt(i);\n                if (seen.containsKey(c) && seen.get(c) >= start) start = seen.get(c) + 1;\n                seen.put(c, i); max = Math.max(max, i - start + 1);\n            }\n            System.out.println(max);\n        }\n    }\n}`,
    },
  },
  {
    day: 20,
    week: 3,
    difficulty: "Medium",
    title: "Binary Search",
    description: "Accept a target element followed by space-separated sorted elements. Print the index (0-based) of the target, or -1 if not found.",
    exampleInput1: "5 1 3 5 7 9",
    exampleOutput1: "2",
    exampleInput2: "2 1 3 5 7 9",
    exampleOutput2: "-1",
    maxExecutionTime: 2000,
    testCases: [
      { input: "5 1 3 5 7 9", output: "2", isHidden: false },
      { input: "2 1 3 5 7 9", output: "-1", isHidden: false },
      { input: "9 1 3 5 7 9", output: "4", isHidden: true },
      { input: "1 1", output: "0", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nconst target = input[0]; const nums = input.slice(1);\nconsole.log(nums.indexOf(target));`,
      python: `import sys\nvals = list(map(int, sys.stdin.read().strip().split()))\ntarget = vals[0]; nums = vals[1:]\ntry: print(nums.index(target))\nexcept: print(-1)`,
      c: `#include <stdio.h>\nint main() {\n    int target, arr[1000], n = 0; if (scanf("%d", &target) == 1) {\n        while (scanf("%d", &arr[n]) != EOF) n++;\n        int idx = -1; for(int i=0; i<n; i++) if (arr[i] == target) { idx = i; break; }\n        printf("%d\\n", idx);\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    int target, val; if (cin >> target) {\n        vector<int> nums; while (cin >> val) nums.push_back(val);\n        int idx = -1; for(size_t i=0; i<nums.size(); i++) if(nums[i]==target) { idx=i; break; }\n        cout << idx << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int target = sc.nextInt(); List<Integer> nums = new ArrayList<>();\n            while (sc.hasNextInt()) nums.add(sc.nextInt());\n            System.out.println(nums.indexOf(target));\n        }\n    }\n}`,
    },
  },

  // DAYS 21 to 30 - HARD
  {
    day: 21,
    week: 4,
    difficulty: "Hard",
    title: "Merge Overlapping Intervals",
    description: "Accept N (number of intervals) followed by N pairs of integers. Merge overlapping intervals and print the sorted merged pairs space-separated.",
    exampleInput1: "4 1 3 2 6 8 10 15 18",
    exampleOutput1: "1 6 8 10 15 18",
    exampleInput2: "2 1 4 4 5",
    exampleOutput2: "1 5",
    maxExecutionTime: 2000,
    testCases: [
      { input: "4 1 3 2 6 8 10 15 18", output: "1 6 8 10 15 18", isHidden: false },
      { input: "2 1 4 4 5", output: "1 5", isHidden: false },
      { input: "3 1 3 4 5 7 8", output: "1 3 4 5 7 8", isHidden: true },
      { input: "3 1 10 2 6 8 9", output: "1 10", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nconst n = input[0]; const intervals = [];\nfor(let i=0; i<n; i++) intervals.push([input[1 + i*2], input[2 + i*2]]);\nintervals.sort((a,b)=>a[0]-b[0]); const merged = [intervals[0]];\nfor(let i=1; i<intervals.length; i++) {\n    const curr = intervals[i]; const last = merged[merged.length-1];\n    if (curr[0] <= last[1]) last[1] = Math.max(last[1], curr[1]);\n    else merged.push(curr);\n}\nconst out = []; merged.forEach(iv => out.push(iv[0], iv[1]));\nconsole.log(out.join(' '));`,
      python: `import sys\nvals = list(map(int, sys.stdin.read().strip().split()))\nn = vals[0]; intervals = []\nfor i in range(n): intervals.append([vals[1 + i*2], vals[2 + i*2]])\nintervals.sort(key=lambda x: x[0]); merged = [intervals[0]]\nfor curr in intervals[1:]:\n    last = merged[-1]\n    if curr[0] <= last[1]: last[1] = max(last[1], curr[1])\n    else: merged.append(curr)\nout = []\nfor iv in merged: out.extend(iv)\nprint(' '.join(map(str, out)))`,
      c: `#include <stdio.h>\n#include <stdlib.h>\nstruct Interval { int start; int end; };\nint cmp(const void* a, const void* b) { return ((struct Interval*)a)->start - ((struct Interval*)b)->start; }\nint main() {\n    int n; if (scanf("%d", &n) == 1) {\n        struct Interval ivs[100]; for (int i = 0; i < n; i++) scanf("%d %d", &ivs[i].start, &ivs[i].end);\n        qsort(ivs, n, sizeof(struct Interval), cmp);\n        struct Interval merged[100]; int count = 0; merged[count++] = ivs[0];\n        for (int i = 1; i < n; i++) {\n            if (ivs[i].start <= merged[count-1].end) {\n                if (ivs[i].end > merged[count-1].end) merged[count-1].end = ivs[i].end;\n            } else merged[count++] = ivs[i];\n        }\n        for (int i = 0; i < count; i++) {\n            printf("%d %d", merged[i].start, merged[i].end); if (i < count - 1) printf(" ");\n        }\n        printf("\\n");\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\nint main() {\n    int n; if (cin >> n) {\n        vector<pair<int, int>> ivs(n); for (int i = 0; i < n; i++) cin >> ivs[i].first >> ivs[i].second;\n        sort(ivs.begin(), ivs.end()); vector<pair<int, int>> merged; merged.push_back(ivs[0]);\n        for (int i = 1; i < n; i++) {\n            if (ivs[i].first <= merged.back().second) merged.back().second = max(merged.back().second, ivs[i].second);\n            else merged.push_back(ivs[i]);\n        }\n        for (size_t i = 0; i < merged.size(); i++) {\n            cout << merged[i].first << " " << merged[i].second; if (i < merged.size() - 1) cout << " ";\n        }\n        cout << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int n = sc.nextInt(); int[][] ivs = new int[n][2];\n            for (int i = 0; i < n; i++) { ivs[i][0] = sc.nextInt(); ivs[i][1] = sc.nextInt(); }\n            Arrays.sort(ivs, (a, b) -> Integer.compare(a[0], b[0]));\n            List<int[]> merged = new ArrayList<>(); merged.add(ivs[0]);\n            for (int i = 1; i < n; i++) {\n                int[] last = merged.get(merged.size() - 1);\n                if (ivs[i][0] <= last[1]) last[1] = Math.max(last[1], ivs[i][1]);\n                else merged.add(ivs[i]);\n            }\n            StringBuilder sb = new StringBuilder();\n            for (int i = 0; i < merged.size(); i++) {\n                sb.append(merged.get(i)[0]).append(" ").append(merged.get(i)[1]);\n                if (i < merged.size() - 1) sb.append(" ");\n            }\n            System.out.println(sb.toString());\n        }\n    }\n}`,
    },
  },
  {
    day: 22,
    week: 4,
    difficulty: "Hard",
    title: "Search Rotated Sorted Array",
    description: "Accept target followed by space-separated elements of a rotated sorted array. Print index (0-based) of the target, or -1.",
    exampleInput1: "0 4 5 6 7 0 1 2",
    exampleOutput1: "4",
    exampleInput2: "3 4 5 6 7 0 1 2",
    exampleOutput2: "-1",
    maxExecutionTime: 2000,
    testCases: [
      { input: "0 4 5 6 7 0 1 2", output: "4", isHidden: false },
      { input: "3 4 5 6 7 0 1 2", output: "-1", isHidden: false },
      { input: "5 5 1 2 3 4", output: "0", isHidden: true },
      { input: "2 3 1", output: "-1", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nconst target = input[0]; const nums = input.slice(1);\nconsole.log(nums.indexOf(target));`,
      python: `import sys\nvals = list(map(int, sys.stdin.read().strip().split()))\ntarget = vals[0]; nums = vals[1:]\ntry: print(nums.index(target))\nexcept: print(-1)`,
      c: `#include <stdio.h>\nint main() {\n    int target, arr[1000], n = 0; if (scanf("%d", &target) == 1) {\n        while (scanf("%d", &arr[n]) != EOF) n++;\n        int idx = -1; for (int i = 0; i < n; i++) if (arr[i] == target) { idx = i; break; }\n        printf("%d\\n", idx);\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    int target, val; if (cin >> target) {\n        vector<int> nums; while (cin >> val) nums.push_back(val);\n        int idx = -1; for (size_t i = 0; i < nums.size(); i++) if (nums[i] == target) { idx = i; break; }\n        cout << idx << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int target = sc.nextInt(); List<Integer> nums = new ArrayList<>();\n            while (sc.hasNextInt()) nums.add(sc.nextInt());\n            System.out.println(nums.indexOf(target));\n        }\n    }\n}`,
    },
  },
  {
    day: 23,
    week: 4,
    difficulty: "Hard",
    title: "Binary Tree Path Sum",
    description: "Accept target sum followed by tree nodes in level-order (-1 representing null). Print Yes if a path matches target sum, else No.",
    exampleInput1: "22 5 4 8 11 -1 13 4 7 2 -1 -1 -1 1",
    exampleOutput1: "Yes",
    exampleInput2: "10 1 2 -1 -1 3 -1",
    exampleOutput2: "No",
    maxExecutionTime: 2000,
    testCases: [
      { input: "22 5 4 8 11 -1 13 4 7 2 -1 -1 -1 1", output: "Yes", isHidden: false },
      { input: "10 1 2 -1 -1 3 -1", output: "No", isHidden: false },
      { input: "5 5", output: "Yes", isHidden: true },
      { input: "10 5 5", output: "Yes", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst vals = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nconst target = vals[0]; const nodes = vals.slice(1);\nif(nodes.length === 0 || nodes[0] === -1) { console.log("No"); process.exit(0); }\nlet hasPath = false;\nfunction dfs(idx, currentSum) {\n    if (idx >= nodes.length || nodes[idx] === -1) return;\n    const sum = currentSum + nodes[idx];\n    const left = idx * 2 + 1; const right = idx * 2 + 2;\n    const isLeaf = (left >= nodes.length || nodes[left] === -1) && (right >= nodes.length || nodes[right] === -1);\n    if (isLeaf) { if (sum === target) hasPath = true; return; }\n    dfs(left, sum); dfs(right, sum);\n}\ndfs(0, 0); console.log(hasPath ? "Yes" : "No");`,
      python: `import sys\nvals = list(map(int, sys.stdin.read().strip().split()))\ntarget = vals[0]; nodes = vals[1:]\nif not nodes or nodes[0] == -1: print("No"); sys.exit(0)\nhas_path = False\ndef dfs(idx, current_sum):\n    global has_path\n    if idx >= len(nodes) or nodes[idx] == -1: return\n    sum_val = current_sum + nodes[idx]\n    left = idx * 2 + 1; right = idx * 2 + 2\n    is_leaf = (left >= len(nodes) or nodes[left] == -1) and (right >= len(nodes) or nodes[right] == -1)\n    if is_leaf:\n        if sum_val == target: has_path = True\n        return\n    dfs(left, sum_val); dfs(right, sum_val)\ndfs(0, 0)\nprint("Yes" if has_path else "No")`,
      c: `#include <stdio.h>\nint target, nodes[1000], size = 0, hasPath = 0;\nvoid dfs(int idx, int sum) {\n    if (idx >= size || nodes[idx] == -1) return;\n    int newSum = sum + nodes[idx];\n    int left = idx * 2 + 1; int right = idx * 2 + 2;\n    int isLeaf = (left >= size || nodes[left] == -1) && (right >= size || nodes[right] == -1);\n    if (isLeaf) { if (newSum == target) hasPath = 1; return; }\n    dfs(left, newSum); dfs(right, newSum);\n}\nint main() {\n    if (scanf("%d", &target) == 1) {\n        while (scanf("%d", &nodes[size]) != EOF) size++;\n        if (size == 0 || nodes[0] == -1) { printf("No\\n"); return 0; }\n        dfs(0, 0); printf("%s\\n", hasPath ? "Yes" : "No");\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <vector>\nusing namespace std;\nint target; vector<int> nodes; bool hasPath = false;\nvoid dfs(int idx, int sum) {\n    if (idx >= nodes.size() || nodes[idx] == -1) return;\n    int newSum = sum + nodes[idx];\n    int left = idx * 2 + 1; int right = idx * 2 + 2;\n    bool isLeaf = (left >= nodes.size() || nodes[left] == -1) && (right >= nodes.size() || nodes[right] == -1);\n    if (isLeaf) { if (newSum == target) hasPath = true; return; }\n    dfs(left, newSum); dfs(right, newSum);\n}\nint main() {\n    if (cin >> target) {\n        int val; while (cin >> val) nodes.push_back(val);\n        if (nodes.empty() || nodes[0] == -1) { cout << "No" << endl; return 0; }\n        dfs(0, 0); cout << (hasPath ? "Yes" : "No") << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    static int target; static List<Integer> nodes = new ArrayList<>(); static boolean hasPath = false;\n    static void dfs(int idx, int sum) {\n        if (idx >= nodes.size() || nodes.get(idx) == -1) return;\n        int newSum = sum + nodes.get(idx);\n        int left = idx * 2 + 1; int right = idx * 2 + 2;\n        boolean isLeaf = (left >= nodes.size() || nodes.get(left) == -1) && (right >= nodes.size() || nodes.get(right) == -1);\n        if (isLeaf) { if (newSum == target) hasPath = true; return; }\n        dfs(left, newSum); dfs(right, newSum);\n    }\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            target = sc.nextInt();\n            while (sc.hasNextInt()) nodes.add(sc.nextInt());\n            if (nodes.isEmpty() || nodes.get(0) == -1) { System.out.println("No"); return; }\n            dfs(0, 0); System.out.println(hasPath ? "Yes" : "No");\n        }\n    }\n}`,
    },
  },
  {
    day: 24,
    week: 4,
    difficulty: "Hard",
    title: "Edit Distance",
    description: "Accept two words. Find the minimum operations (insert, delete, replace) to convert word 1 to word 2.",
    exampleInput1: "horse ros",
    exampleOutput1: "3",
    exampleInput2: "intention execution",
    exampleOutput2: "5",
    maxExecutionTime: 2000,
    testCases: [
      { input: "horse ros", output: "3", isHidden: false },
      { input: "intention execution", output: "5", isHidden: false },
      { input: "abc abc", output: "0", isHidden: true },
      { input: "a b", output: "1", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst [w1, w2] = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);\nconst dp = Array(w1.length + 1).fill(null).map(() => Array(w2.length + 1).fill(0));\nfor(let i=0; i<=w1.length; i++) dp[i][0] = i;\nfor(let j=0; j<=w2.length; j++) dp[0][j] = j;\nfor(let i=1; i<=w1.length; i++) {\n    for(let j=1; j<=w2.length; j++) {\n        if (w1[i-1] === w2[j-1]) dp[i][j] = dp[i-1][j-1];\n        else dp[i][j] = 1 + Math.min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]);\n    }\n}\nconsole.log(dp[w1.length][w2.length]);`,
      python: `import sys\nw1, w2 = sys.stdin.read().strip().split()\ndp = [[0] * (len(w2) + 1) for _ in range(len(w1) + 1)]\nfor i in range(len(w1) + 1): dp[i][0] = i\nfor j in range(len(w2) + 1): dp[0][j] = j\nfor i in range(1, len(w1) + 1):\n    for j in range(1, len(w2) + 1):\n        if w1[i-1] == w2[j-1]: dp[i][j] = dp[i-1][j-1]\n        else: dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\nprint(dp[len(w1)][len(w2)])`,
      c: `#include <stdio.h>\n#include <string.h>\nint min(int a, int b, int c) {\n    int m = a; if (b < m) m = b; if (c < m) m = c; return m;\n}\nint main() {\n    char w1[100], w2[100]; if (scanf("%s %s", w1, w2) == 2) {\n        int l1 = strlen(w1), l2 = strlen(w2); int dp[101][101];\n        for (int i = 0; i <= l1; i++) dp[i][0] = i;\n        for (int j = 0; j <= l2; j++) dp[0][j] = j;\n        for (int i = 1; i <= l1; i++) {\n            for (int j = 1; j <= l2; j++) {\n                if (w1[i-1] == w2[j-1]) dp[i][j] = dp[i-1][j-1];\n                else dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]);\n            }\n        }\n        printf("%d\\n", dp[l1][l2]);\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <string>\n#include <vector>\n#include <algorithm>\nusing namespace std;\nint main() {\n    string w1, w2; if (cin >> w1 >> w2) {\n        int l1 = w1.length(), l2 = w2.length(); vector<vector<int>> dp(l1 + 1, vector<int>(l2 + 1));\n        for (int i = 0; i <= l1; i++) dp[i][0] = i;\n        for (int j = 0; j <= l2; j++) dp[0][j] = j;\n        for (int i = 1; i <= l1; i++) {\n            for (int j = 1; j <= l2; j++) {\n                if (w1[i-1] == w2[j-1]) dp[i][j] = dp[i-1][j-1];\n                else dp[i][j] = 1 + min({dp[i-1][j], dp[i][j-1], dp[i-1][j-1]});\n            }\n        }\n        cout << dp[l1][l2] << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNext()) {\n            String w1 = sc.next(); String w2 = sc.next(); int l1 = w1.length(), l2 = w2.length();\n            int[][] dp = new int[l1 + 1][l2 + 1];\n            for (int i = 0; i <= l1; i++) dp[i][0] = i;\n            for (int j = 0; j <= l2; j++) dp[0][j] = j;\n            for (int i = 1; i <= l1; i++) {\n                for (int j = 1; j <= l2; j++) {\n                    if (w1.charAt(i-1) == w2.charAt(j-1)) dp[i][j] = dp[i-1][j-1];\n                    else dp[i][j] = 1 + Math.min(dp[i-1][j], Math.min(dp[i][j-1], dp[i-1][j-1]));\n                }\n            }\n            System.out.println(dp[l1][l2]);\n        }\n    }\n}`,
    },
  },
  {
    day: 25,
    week: 4,
    difficulty: "Hard",
    title: "Knapsack 0/1",
    description: "Accept N (items), W (Capacity), followed by N weights, then N values. Print the max value.",
    exampleInput1: "3 50 10 20 30 60 100 120",
    exampleOutput1: "220",
    exampleInput2: "4 10 1 3 4 6 20 30 10 50",
    exampleOutput2: "100",
    maxExecutionTime: 2000,
    testCases: [
      { input: "3 50 10 20 30 60 100 120", output: "220", isHidden: false },
      { input: "4 10 1 3 4 6 20 30 10 50", output: "100", isHidden: false },
      { input: "1 10 5 100", output: "100", isHidden: true },
      { input: "2 5 10 20 1 2", output: "0", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nconst n = input[0], cap = input[1]; const wt = input.slice(2, 2 + n); const val = input.slice(2 + n);\nconst dp = Array(n + 1).fill(null).map(() => Array(cap + 1).fill(0));\nfor(let i=1; i<=n; i++) {\n    for(let w=1; w<=cap; w++) {\n        if (wt[i-1] <= w) dp[i][w] = Math.max(val[i-1] + dp[i-1][w-wt[i-1]], dp[i-1][w]);\n        else dp[i][w] = dp[i-1][w];\n    }\n}\nconsole.log(dp[n][cap]);`,
      python: `import sys\nvals = list(map(int, sys.stdin.read().strip().split()))\nn, cap = vals[0], vals[1]; wt = vals[2 : 2 + n]; val = vals[2 + n :]\ndp = [[0] * (cap + 1) for _ in range(n + 1)]\nfor i in range(1, n + 1):\n    for w in range(1, cap + 1):\n        if wt[i-1] <= w: dp[i][w] = max(val[i-1] + dp[i-1][w-wt[i-1]], dp[i-1][w])\n        else: dp[i][w] = dp[i-1][w]\nprint(dp[n][cap])`,
      c: `#include <stdio.h>\nint max(int a, int b) { return a > b ? a : b; }\nint main() {\n    int n, cap; if (scanf("%d %d", &n, &cap) == 2) {\n        int wt[100], val[100];\n        for (int i = 0; i < n; i++) scanf("%d", &wt[i]);\n        for (int i = 0; i < n; i++) scanf("%d", &val[i]);\n        int dp[101][1001] = {0};\n        for (int i = 1; i <= n; i++) {\n            for (int w = 1; w <= cap; w++) {\n                if (wt[i-1] <= w) dp[i][w] = max(val[i-1] + dp[i-1][w-wt[i-1]], dp[i-1][w]);\n                else dp[i][w] = dp[i-1][w];\n            }\n        }\n        printf("%d\\n", dp[n][cap]);\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\nint main() {\n    int n, cap; if (cin >> n >> cap) {\n        vector<int> wt(n), val(n); for (int i = 0; i < n; i++) cin >> wt[i];\n        for (int i = 0; i < n; i++) cin >> val[i];\n        vector<vector<int>> dp(n + 1, vector<int>(cap + 1, 0));\n        for (int i = 1; i <= n; i++) {\n            for (int w = 1; w <= cap; w++) {\n                if (wt[i-1] <= w) dp[i][w] = max(val[i-1] + dp[i-1][w-wt[i-1]], dp[i-1][w]);\n                else dp[i][w] = dp[i-1][w];\n            }\n        }\n        cout << dp[n][cap] << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.Scanner;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int n = sc.nextInt(); int cap = sc.nextInt();\n            int[] wt = new int[n]; for (int i = 0; i < n; i++) wt[i] = sc.nextInt();\n            int[] val = new int[n]; for (int i = 0; i < n; i++) val[i] = sc.nextInt();\n            int[][] dp = new int[n + 1][cap + 1];\n            for (int i = 1; i <= n; i++) {\n                for (int w = 1; w <= cap; w++) {\n                    if (wt[i-1] <= w) dp[i][w] = Math.max(val[i-1] + dp[i-1][w-wt[i-1]], dp[i-1][w]);\n                    else dp[i][w] = dp[i-1][w];\n                }\n            }\n            System.out.println(dp[n][cap]);\n        }\n    }\n}`,
    },
  },
  {
    day: 26,
    week: 4,
    difficulty: "Hard",
    title: "Longest Common Subsequence",
    description: "Accept two space-separated strings. Print the length of their longest common subsequence.",
    exampleInput1: "abcde ace",
    exampleOutput1: "3",
    exampleInput2: "abc def",
    exampleOutput2: "0",
    maxExecutionTime: 2000,
    testCases: [
      { input: "abcde ace", output: "3", isHidden: false },
      { input: "abc def", output: "0", isHidden: false },
      { input: "a a", output: "1", isHidden: true },
      { input: "AGGTAB GXTXAYB", output: "4", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst [s1, s2] = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);\nconst dp = Array(s1.length + 1).fill(null).map(() => Array(s2.length + 1).fill(0));\nfor(let i=1; i<=s1.length; i++) {\n    for(let j=1; j<=s2.length; j++) {\n        if (s1[i-1] === s2[j-1]) dp[i][j] = 1 + dp[i-1][j-1];\n        else dp[i][j] = Math.max(dp[i-1][j], dp[i][j-1]);\n    }\n}\nconsole.log(dp[s1.length][s2.length]);`,
      python: `import sys\nval = sys.stdin.read().strip().split()\ns1, s2 = val[0], val[1]\ndp = [[0] * (len(s2) + 1) for _ in range(len(s1) + 1)]\nfor i in range(1, len(s1) + 1):\n    for j in range(1, len(s2) + 1):\n        if s1[i-1] == s2[j-1]: dp[i][j] = 1 + dp[i-1][j-1]\n        else: dp[i][j] = max(dp[i-1][j], dp[i][j-1])\nprint(dp[len(s1)][len(s2)])`,
      c: `#include <stdio.h>\n#include <string.h>\nint max(int a, int b) { return a > b ? a : b; }\nint main() {\n    char s1[100], s2[100]; if (scanf("%s %s", s1, s2) == 2) {\n        int l1 = strlen(s1), l2 = strlen(s2); int dp[101][101] = {0};\n        for(int i=1; i<=l1; i++) {\n            for(int j=1; j<=l2; j++) {\n                if(s1[i-1] == s2[j-1]) dp[i][j] = 1 + dp[i-1][j-1];\n                else dp[i][j] = max(dp[i-1][j], dp[i][j-1]);\n            }\n        }\n        printf("%d\\n", dp[l1][l2]);\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <string>\n#include <vector>\n#include <algorithm>\nusing namespace std;\nint main() {\n    string s1, s2; if (cin >> s1 >> s2) {\n        int l1 = s1.length(), l2 = s2.length(); vector<vector<int>> dp(l1 + 1, vector<int>(l2 + 1, 0));\n        for(int i=1; i<=l1; i++) {\n            for(int j=1; j<=l2; j++) {\n                if(s1[i-1] == s2[j-1]) dp[i][j] = 1 + dp[i-1][j-1];\n                else dp[i][j] = max(dp[i-1][j], dp[i][j-1]);\n            }\n        }\n        cout << dp[l1][l2] << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNext()) {\n            String s1 = sc.next(); String s2 = sc.next();\n            int l1 = s1.length(), l2 = s2.length(); int[][] dp = new int[l1+1][l2+1];\n            for(int i=1; i<=l1; i++) {\n                for(int j=1; j<=l2; j++) {\n                    if(s1.charAt(i-1) == s2.charAt(j-1)) dp[i][j] = 1 + dp[i-1][j-1];\n                    else dp[i][j] = Math.max(dp[i-1][j], dp[i][j-1]);\n                }\n            }\n            System.out.println(dp[l1][l2]);\n        }\n    }\n}`,
    },
  },
  {
    day: 27,
    week: 4,
    difficulty: "Hard",
    title: "Coin Change Problem",
    description: "Accept target sum followed by count N and N space-separated coin denominations. Print the minimum number of coins needed to make target. If not possible, print -1.",
    exampleInput1: "11 3 1 2 5",
    exampleOutput1: "3",
    exampleInput2: "3 1 2",
    exampleOutput2: "-1",
    maxExecutionTime: 2000,
    testCases: [
      { input: "11 3 1 2 5", output: "3", isHidden: false },
      { input: "3 1 2", output: "-1", isHidden: false },
      { input: "0 2 1 2", output: "0", isHidden: true },
      { input: "30 3 5 10 25", output: "2", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nconst target = input[0]; const coins = input.slice(2);\nconst dp = Array(target + 1).fill(Infinity); dp[0] = 0;\nfor(let i=1; i<=target; i++) {\n    for(let coin of coins) {\n        if (i - coin >= 0) dp[i] = Math.min(dp[i], 1 + dp[i - coin]);\n    }\n}\nconsole.log(dp[target] === Infinity ? -1 : dp[target]);`,
      python: `import sys\nvals = list(map(int, sys.stdin.read().strip().split()))\ntarget = vals[0]; coins = vals[2:]\ndp = [float('inf')] * (target + 1); dp[0] = 0\nfor i in range(1, target + 1):\n    for coin in coins:\n        if i - coin >= 0: dp[i] = min(dp[i], 1 + dp[i - coin])\nprint(-1 if dp[target] == float('inf') else dp[target])`,
      c: `#include <stdio.h>\n#define INF 999999\nint main() {\n    int target, n; if (scanf("%d %d", &target, &n) == 2) {\n        int coins[100]; for (int i = 0; i < n; i++) scanf("%d", &coins[i]);\n        int dp[10001]; dp[0] = 0; for (int i = 1; i <= target; i++) dp[i] = INF;\n        for (int i = 1; i <= target; i++) {\n            for (int j = 0; j < n; j++) {\n                if (i - coins[j] >= 0) {\n                    int val = 1 + dp[i - coins[j]]; if (val < dp[i]) dp[i] = val;\n                }\n            }\n        }\n        printf("%d\\n", dp[target] >= INF ? -1 : dp[target]);\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\nint main() {\n    int target, n; if (cin >> target >> n) {\n        vector<int> coins(n); for (int i = 0; i < n; i++) cin >> coins[i];\n        vector<int> dp(target + 1, 999999); dp[0] = 0;\n        for (int i = 1; i <= target; i++) {\n            for (int c : coins) if (i - c >= 0) dp[i] = min(dp[i], 1 + dp[i - c]);\n        }\n        cout << (dp[target] >= 999999 ? -1 : dp[target]) << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int target = sc.nextInt(); int n = sc.nextInt();\n            int[] coins = new int[n]; for (int i = 0; i < n; i++) coins[i] = sc.nextInt();\n            int[] dp = new int[target + 1]; Arrays.fill(dp, 999999); dp[0] = 0;\n            for (int i = 1; i <= target; i++) {\n                for (int c : coins) if (i - c >= 0) dp[i] = Math.min(dp[i], 1 + dp[i - c]);\n            }\n            System.out.println(dp[target] >= 999999 ? -1 : dp[target]);\n        }\n    }\n}`,
    },
  },
  {
    day: 28,
    week: 4,
    difficulty: "Hard",
    title: "Word Break",
    description: "Accept a string target, followed by count N and N space-separated dictionary words. Print Yes if the target string can be segmented into space-separated dictionary words, else print No.",
    exampleInput1: "leetcode 2 leet code",
    exampleOutput1: "Yes",
    exampleInput2: "catsandog 5 cats dog sand and cat",
    exampleOutput2: "No",
    maxExecutionTime: 2000,
    testCases: [
      { input: "leetcode 2 leet code", output: "Yes", isHidden: false },
      { input: "catsandog 5 cats dog sand and cat", output: "No", isHidden: false },
      { input: "applepenapple 2 apple pen", output: "Yes", isHidden: true },
      { input: "a 1 b", output: "No", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);\nconst target = input[0]; const dict = new Set(input.slice(2));\nconst dp = Array(target.length + 1).fill(false); dp[0] = true;\nfor (let i = 1; i <= target.length; i++) {\n    for (let j = 0; j < i; j++) {\n        if (dp[j] && dict.has(target.substring(j, i))) { dp[i] = true; break; }\n    }\n}\nconsole.log(dp[target.length] ? "Yes" : "No");`,
      python: `import sys\nvals = sys.stdin.read().strip().split()\ntarget = vals[0]; words = set(vals[2:])\ndp = [False] * (len(target) + 1); dp[0] = True\nfor i in range(1, len(target) + 1):\n    for j in range(i):\n        if dp[j] and target[j:i] in words:\n            dp[i] = True; break\nprint("Yes" if dp[len(target)] else "No")`,
      c: `#include <stdio.h>\n#include <string.h>\nint main() {\n    char target[100]; int n; if (scanf("%s %d", target, &n) == 2) {\n        char dict[50][50]; for (int i = 0; i < n; i++) scanf("%s", dict[i]);\n        int len = strlen(target); int dp[101] = {0}; dp[0] = 1;\n        for (int i = 1; i <= len; i++) {\n            for (int j = 0; j < i; j++) {\n                if (dp[j]) {\n                    char sub[100]; strncpy(sub, target + j, i - j); sub[i - j] = '\\0';\n                    int match = 0; for (int k = 0; k < n; k++) if (strcmp(sub, dict[k]) == 0) match = 1;\n                    if (match) { dp[i] = 1; break; }\n                }\n            }\n        }\n        printf("%s\\n", dp[len] ? "Yes" : "No");\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <string>\n#include <vector>\n#include <unordered_set>\nusing namespace std;\nint main() {\n    string target; int n; if (cin >> target >> n) {\n        unordered_set<string> dict; for (int i = 0; i < n; i++) { string w; cin >> w; dict.insert(w); }\n        vector<bool> dp(target.length() + 1, false); dp[0] = true;\n        for (size_t i = 1; i <= target.length(); i++) {\n            for (size_t j = 0; j < i; j++) {\n                if (dp[j] && dict.count(target.substr(j, i - j))) { dp[i] = true; break; }\n            }\n        }\n        cout << (dp[target.length()] ? "Yes" : "No") << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNext()) {\n            String target = sc.next(); int n = sc.nextInt();\n            Set<String> dict = new HashSet<>(); for (int i = 0; i < n; i++) dict.add(sc.next());\n            boolean[] dp = new boolean[target.length() + 1]; dp[0] = true;\n            for (int i = 1; i <= target.length(); i++) {\n                for (int j = 0; j < i; j++) {\n                    if (dp[j] && dict.contains(target.substring(j, i))) { dp[i] = true; break; }\n                }\n            }\n            System.out.println(dp[target.length()] ? "Yes" : "No");\n        }\n    }\n}`,
    },
  },
  {
    day: 29,
    week: 4,
    difficulty: "Hard",
    title: "N-Queens Solutions",
    description: "Accept board size N (integer). Print the total number of distinct solutions to place N queens on an N*N chessboard such that no two queens attack each other.",
    exampleInput1: "4",
    exampleOutput1: "2",
    exampleInput2: "1",
    exampleOutput2: "1",
    maxExecutionTime: 2000,
    testCases: [
      { input: "4", output: "2", isHidden: false },
      { input: "1", output: "1", isHidden: false },
      { input: "8", output: "92", isHidden: true },
      { input: "2", output: "0", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst n = parseInt(fs.readFileSync(0, 'utf-8').trim());\nlet count = 0;\nfunction solve(row, cols, diag1, diag2) {\n    if (row === n) { count++; return; }\n    for (let col = 0; col < n; col++) {\n        const d1 = row - col; const d2 = row + col;\n        if (cols.has(col) || diag1.has(d1) || diag2.has(d2)) continue;\n        cols.add(col); diag1.add(d1); diag2.add(d2);\n        solve(row + 1, cols, diag1, diag2);\n        cols.delete(col); diag1.delete(d1); diag2.delete(d2);\n    }\n}\nsolve(0, new Set(), new Set(), new Set());\nconsole.log(count);`,
      python: `import sys\nn = int(sys.stdin.read().strip())\ncount = 0\ndef solve(row, cols, diag1, diag2):\n    global count\n    if row == n: count += 1; return\n    for col in range(n):\n        d1, d2 = row - col, row + col\n        if col in cols or d1 in diag1 or d2 in diag2: continue\n        cols.add(col); diag1.add(d1); diag2.add(d2)\n        solve(row + 1, cols, diag1, diag2)\n        cols.remove(col); diag1.remove(d1); diag2.remove(d2)\nsolve(0, set(), set(), set())\nprint(count)`,
      c: `#include <stdio.h>\nint n, count = 0, cols[20], diag1[40], diag2[40];\nvoid solve(int row) {\n    if (row == n) { count++; return; }\n    for (int col = 0; col < n; col++) {\n        int d1 = row - col + 10; int d2 = row + col;\n        if (cols[col] || diag1[d1] || diag2[d2]) continue;\n        cols[col] = diag1[d1] = diag2[d2] = 1;\n        solve(row + 1);\n        cols[col] = diag1[d1] = diag2[d2] = 0;\n    }\n}\nint main() {\n    if (scanf("%d", &n) == 1) { solve(0); printf("%d\\n", count); }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <vector>\n#include <set>\nusing namespace std;\nint n, total = 0;\nvoid solve(int row, set<int>& cols, set<int>& diag1, set<int>& diag2) {\n    if (row == n) { total++; return; }\n    for (int col = 0; col < n; col++) {\n        int d1 = row - col; int d2 = row + col;\n        if (cols.count(col) || diag1.count(d1) || diag2.count(d2)) continue;\n        cols.insert(col); diag1.insert(d1); diag2.insert(d2);\n        solve(row + 1, cols, diag1, diag2);\n        cols.erase(col); diag1.erase(d1); diag2.erase(d2);\n    }\n}\nint main() {\n    if (cin >> n) { set<int> c, d1, d2; solve(0, c, d1, d2); cout << total << endl; }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    static int n, count = 0;\n    static Set<Integer> cols = new HashSet<>(); static Set<Integer> d1 = new HashSet<>(); static Set<Integer> d2 = new HashSet<>();\n    static void solve(int row) {\n        if (row == n) { count++; return; }\n        for (int col = 0; col < n; col++) {\n            int diag1 = row - col; int diag2 = row + col;\n            if (cols.contains(col) || d1.contains(diag1) || d2.contains(diag2)) continue;\n            cols.add(col); d1.add(diag1); d2.add(diag2);\n            solve(row + 1);\n            cols.remove(col); d1.remove(diag1); d2.remove(diag2);\n        }\n    }\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) { n = sc.nextInt(); solve(0); System.out.println(count); }\n    }\n}`,
    },
  },
  {
    day: 30,
    week: 4,
    difficulty: "Hard",
    title: "Median of Sorted Arrays",
    description: "Accept sizes R and C of two sorted arrays, followed by R sorted integers for array 1 and C sorted integers for array 2. Print the median value as a float with 1 decimal place (e.g. 2.0 or 2.5).",
    exampleInput1: "2 1 1 3 2",
    exampleOutput1: "2.0",
    exampleInput2: "2 2 1 2 3 4",
    exampleOutput2: "2.5",
    maxExecutionTime: 2000,
    testCases: [
      { input: "2 1 1 3 2", output: "2.0", isHidden: false },
      { input: "2 2 1 2 3 4", output: "2.5", isHidden: false },
      { input: "3 2 1 3 5 2 4", output: "3.0", isHidden: true },
      { input: "1 1 10 20", output: "15.0", isHidden: true },
    ],
    templates: {
      javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nconst r = input[0], c = input[1];\nconst a1 = input.slice(2, 2 + r);\nconst a2 = input.slice(2 + r);\nconst merged = [...a1, ...a2].sort((a,b)=>a-b);\nconst len = merged.length;\nconst median = len % 2 === 0 ? (merged[len/2 - 1] + merged[len/2]) / 2 : merged[Math.floor(len/2)];\nconsole.log(median.toFixed(1));`,
      python: `import sys\nvals = list(map(int, sys.stdin.read().strip().split()))\nr, c = vals[0], vals[1]\na1 = vals[2 : 2 + r]\na2 = vals[2 + r :]\nmerged = sorted(a1 + a2)\nlength = len(merged)\nif length % 2 == 0:\n    median = (merged[length // 2 - 1] + merged[length // 2]) / 2.0\nelse:\n    median = float(merged[length // 2])\nprint(f"{median:.1f}")`,
      c: `#include <stdio.h>\n#include <stdlib.h>\nint cmp(const void* a, const void* b) { return (*(int*)a - *(int*)b); }\nint main() {\n    int r, c; if (scanf("%d %d", &r, &c) == 2) {\n        int arr[2000], size = r + c;\n        for (int i = 0; i < size; i++) scanf("%d", &arr[i]);\n        qsort(arr, size, sizeof(int), cmp);\n        double median = (size % 2 == 0) ? (arr[size/2 - 1] + arr[size/2]) / 2.0 : (double)arr[size/2];\n        printf("%.1f\\n", median);\n    }\n    return 0;\n}`,
      cpp: `#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <iomanip>\nusing namespace std;\nint main() {\n    int r, c; if (cin >> r >> c) {\n        vector<int> arr(r + c); for (int i = 0; i < r + c; i++) cin >> arr[i];\n        sort(arr.begin(), arr.end());\n        double median = (arr.size() % 2 == 0) ? (arr[arr.size()/2 - 1] + arr[arr.size()/2]) / 2.0 : arr[arr.size()/2];\n        cout << fixed << setprecision(1) << median << endl;\n    }\n    return 0;\n}`,
      java: `import java.util.*;\npublic class Temp {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (sc.hasNextInt()) {\n            int r = sc.nextInt(); int c = sc.nextInt();\n            int[] arr = new int[r + c]; for (int i = 0; i < r + c; i++) arr[i] = sc.nextInt();\n            Arrays.sort(arr);\n            double median = (arr.length % 2 == 0) ? (arr[arr.length/2 - 1] + arr[arr.length/2]) / 2.0 : arr[arr.length/2];\n            System.out.printf(Locale.US, "%.1f\\n", median);\n        }\n    }\n}`,
    },
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to database for seeding 30 challenges.");
    
    // Clear existing challenges
    await Challenge.deleteMany({});
    console.log("Cleared existing challenges.");
    
    // Insert new challenges
    await Challenge.insertMany(challenges);
    console.log("Successfully seeded 30 Daily Coding Challenges.");
    
    mongoose.connection.close();
  } catch (error) {
    console.error("Seeding error:", error);
  }
}

seed();
